from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SetDef:
    name: str           # e.g. "com_ts (r,c,s)"
    base_name: str      # e.g. "com_ts"
    aliases: tuple[str, ...]
    indexes: tuple[str, ...]
    description: str
    category: str       # "User Input" or "Internal"


SET_REGISTRY: dict[str, SetDef] = {
    'age': SetDef(
        name='age',
        base_name='age',
        aliases=('life', 'jot'),
        indexes=(),
        description='Index for age (number of years since installation) into a parameter shaping curve; default elements 1–200.',
        category='User Input',
    ),
    'all_r': SetDef(
        name='all_r',
        base_name='all_r',
        aliases=('all_reg',),
        indexes=(),
        description='Set of all regions, internal as well as external; a region is defined as internal by putting it in the internal region set (r), regions that are not member of the internal region set are per definition external.',
        category='User Input',
    ),
    'bd': SetDef(
        name='bd(lim)',
        base_name='bd',
        aliases=(),
        indexes=('lim',),
        description='Index of bound type; subset of the set lim having the internally fixed elements \'LO\', \'UP\', \'FX\'.',
        category='Internal',
    ),
    'c': SetDef(
        name='c (cg)',
        base_name='c',
        aliases=('com', 'com1', 'com2', 'com3'),
        indexes=('cg',),
        description='User defined list of all commodities in all regions; subset of cg.',
        category='User Input',
    ),
    'cg': SetDef(
        name='cg',
        base_name='cg',
        aliases=('com_grp', 'cg1', 'cg2', 'cg3', 'cg4'),
        indexes=(),
        description='User defined list of all commodities and commodity groups (see Figure 2) in all regions.',
        category='User Input',
    ),
    'clu': SetDef(
        name='clu (p)',
        base_name='clu',
        aliases=(),
        indexes=('p',),
        description='Set of cluster technologies in endogenous technology learning.',
        category='User Input',
    ),
    'com_desc': SetDef(
        name='com_desc (r,c)',
        base_name='com_desc',
        aliases=(),
        indexes=('r', 'c'),
        description='Commodities by region, only to facilitate different descriptions by region. The elements are pairs {r,c}, for which the description is specified according to the GAMS syntax.',
        category='User Input',
    ),
    'com_gmap': SetDef(
        name='com_gmap (r,cg,c)',
        base_name='com_gmap',
        aliases=(),
        indexes=('r', 'cg', 'c'),
        description='Mapping of commodity c to user-defined commodity group cg, including itself [set of triplets {r,cg,c} such that commodity c in in group cg in region r].',
        category='User Input',
    ),
    'com_lim': SetDef(
        name='com_lim (r,c,lim)',
        base_name='com_lim',
        aliases=(),
        indexes=('r', 'c', 'lim'),
        description='Definition of commodity balance equation type [set of triplets {r,c,lim} such that commodity c has a balance of type lim (lim=\'UP\',\'LO\',\'FX\', \'N\') in region r]; Default: for commodities of type NRG, DM and ENV production is greater or equal consumption, while for MAT and FIN commodities the balance is a strict equality.',
        category='User Input',
    ),
    'com_off': SetDef(
        name='com_off (r,c,y1,y2)',
        base_name='com_off',
        aliases=(),
        indexes=('r', 'c', 'y1', 'y2'),
        description='Specifying that the commodity c in region r is not available between the years y1 and y2 [set of quadruplets {r,c,y1,y2} such that commodity c is unavailable from years y1 to y1 in region r] ; note that y1 may be \'BOH\' for the first year of the first period and y2 may be \'EOH\' for the last year of the last period.',
        category='User Input',
    ),
    'com_peak': SetDef(
        name='com_peak (r,cg)',
        base_name='com_peak',
        aliases=(),
        indexes=('r', 'cg'),
        description='Set of pairs {r,cg} such that a peaking constraint is to be generated for commodity cg in region r; note that the peaking equation can be generated for a single commodity (cg also contains single commodities c) or for a group of commodities, e.g. electricity commodities differentiated by voltage level.',
        category='User Input',
    ),
    'com_pkts': SetDef(
        name='com_pkts (r,cg,s)',
        base_name='com_pkts',
        aliases=(),
        indexes=('r', 'cg', 's'),
        description='Set of triplets {r,cg,s} such that a peaking constraint for a single commodity or a group of commodities cg (e.g. if the model differentiates between three electricity commodities: electricity on high, middle and low voltage ) is to be generated for the timeslice s; Default: all timeslices of com_ts; note that the peaking constraint will be binding only for the timeslice with the highest load.',
        category='User Input',
    ),
    'com_tmap': SetDef(
        name='com_tmap (r,com_type,c)',
        base_name='com_tmap',
        aliases=(),
        indexes=('r', 'com_type', 'c'),
        description='Mapping of commodities to the main commodity types (see com_type in Table 1); [set of triplets {r,com_type,c} such that commodity c has type com_type];',
        category='User Input',
    ),
    'com_ts': SetDef(
        name='com_ts (r,c,s)',
        base_name='com_ts',
        aliases=(),
        indexes=('r', 'c', 's'),
        description='Set of triplets {r,c,s} such that commodity c is available in timeslice s in region r; commodity balances will be generated for the given timeslices; Default: all timeslices of timeslice level specified by com_tsl.',
        category='User Input',
    ),
    'com_tsl': SetDef(
        name='com_tsl (r,c,tslvl)',
        base_name='com_tsl',
        aliases=(),
        indexes=('r', 'c', 'tslvl'),
        description='Set of triplets {r,c,tslvl} such that commodity c is modelled on the timeslice level tslvl in region r; Default: \'ANNUAL timeslice level.',
        category='User Input',
    ),
    'com_type': SetDef(
        name='com_type',
        base_name='com_type',
        aliases=(),
        indexes=(),
        description='Indicator of commodity type; initialized to the following elements: DEM, NRG, MAT, ENV, FIN. The predefined elements should never be deleted.',
        category='Internal',
    ),
    'com_unit': SetDef(
        name='com_unit (r,c,units_com)',
        base_name='com_unit',
        aliases=(),
        indexes=('r', 'c', 'units_com'),
        description='Set of triplets {r,c,units_com} such that commodity c is expressed in unit units_com in region r.',
        category='User Input',
    ),
    'costagg': SetDef(
        name='costagg',
        base_name='costagg',
        aliases=(),
        indexes=(),
        description='List of cost aggregation types available for user-defined cost constraints: INV, INVTAX, INVSUB, INVTAXSUB, INVALL, FOM, FOMTAX, FOMSUB, FOMTAXSUB, FOMALL, COMTAX, COMSUB, COMTAXSUB, FLOTAX, FLOSUB, FLOTAXSUB, FIX, FIXTAX, FIXSUB, FIXTAXSUB, FIXALL, ALLTAX, ALLSUB, ALLTAXSUB',
        category='Internal',
    ),
    'cur': SetDef(
        name='cur',
        base_name='cur',
        aliases=(),
        indexes=(),
        description='User defined list of currency units.',
        category='User Input',
    ),
    'datayear': SetDef(
        name='datayear (year)',
        base_name='datayear',
        aliases=(),
        indexes=('year',),
        description='Years for which model input data are to be taken; No default.',
        category='User Input',
    ),
    'dem_sect': SetDef(
        name='dem_sect',
        base_name='dem_sect',
        aliases=(),
        indexes=(),
        description='List of demand sectors; internally established in MAPLIST.DEF as: AGR, RES, COM, IND, TRN, NE, OTH. The predefined elements should not be deleted.',
        category='Internal',
    ),
    'dem_smap': SetDef(
        name='dem_smap (r,dem_sect,c)',
        base_name='dem_smap',
        aliases=(),
        indexes=('r', 'dem_sect', 'c'),
        description='Mapping of demands to main demand sectors (see dem_sect in Table 1); [set of triplets {r,dem_sect,c} such that commodity c belongs to sector dem_sect];',
        category='User Input',
    ),
    'env_map': SetDef(
        name='env_map (r,env_grp,c)',
        base_name='env_map',
        aliases=(),
        indexes=('r', 'env_grp', 'c'),
        description='Mapping of environmental commodities to main types (see env_grp in Table 1); [set of triplets {r,env_grp,c} such that commodity c is of type env_grp].',
        category='User Input',
    ),
    'env_type': SetDef(
        name='env_type',
        base_name='env_type',
        aliases=(),
        indexes=(),
        description='List of emission types; internally established in MAPLIST.DEF as: GHG, PEM, OEM, OTHENV',
        category='Internal',
    ),
    'ie': SetDef(
        name='ie',
        base_name='ie',
        aliases=(),
        indexes=(),
        description='Export/import exchange index; internally fixed to the two elements: \'IMP\' standing for import and \'EXP\' standing for export.',
        category='Internal',
    ),
    'io': SetDef(
        name='io',
        base_name='io',
        aliases=(),
        indexes=(),
        description='Input/Output index; internally fixed elements: \'IN\', \'OUT\'; used in combination with processes and commodities as indicator whether a commodity enters or leaves a process.',
        category='Internal',
    ),
    'j': SetDef(
        name='j',
        base_name='j',
        aliases=('jj',),
        indexes=(),
        description='Indicator for elastic demand steps and sequence number of the shape/multi curves; default elements 1–999.',
        category='Internal',
    ),
    'kp': SetDef(
        name='kp',
        base_name='kp',
        aliases=(),
        indexes=(),
        description='Index for “kink” points in ETL formulation; currently limited to 1-6 {can be extended in <case>.run file by including SET KP / 1*n /; for n-kink points.',
        category='Internal',
    ),
    'lim': SetDef(
        name='lim',
        base_name='lim',
        aliases=('lim_type', 'l'),
        indexes=(),
        description='Index of limit types; internally fixed = \'LO\', \'UP\', \'FX\', \'N\'.',
        category='Internal',
    ),
    'nrg_tmap': SetDef(
        name='nrg_tmap (r,nrg_type,c)',
        base_name='nrg_tmap',
        aliases=(),
        indexes=('r', 'nrg_type', 'c'),
        description='Mapping of energy commodities to main types (see nrg_type in Table 1); [set of triplets {r,nrg_type,c} such that commodity c is of type nrg_type].',
        category='User Input',
    ),
    'nrg_type': SetDef(
        name='nrg_type',
        base_name='nrg_type',
        aliases=(),
        indexes=(),
        description='List of energy types; internally established in MAPLIST.DEF as: FOSSIL, NUCLR, SYNTH, FRERENEW, LIMRENEW, ELC, HTHEAT, LTHEAT, CONSRV. The predefined elements should not be deleted.',
        category='Internal',
    ),
    'p': SetDef(
        name='p',
        base_name='p',
        aliases=('prc',),
        indexes=(),
        description='User defined list of all processes in all regions',
        category='User Input',
    ),
    'pastyear': SetDef(
        name='pastyear (year)',
        base_name='pastyear',
        aliases=('pyr',),
        indexes=('year',),
        description='Years for which past investments are specified; pastyears usually lie before the beginning of the first period; No default.',
        category='User Input',
    ),
    'prc_actunt': SetDef(
        name='prc_actunt (r,p,cg,units_act)',
        base_name='prc_actunt',
        aliases=(),
        indexes=('r', 'p', 'cg', 'units_act'),
        description='Definition of activity [Set of quadruples such that the commodity group cg is used to define the activity of the process p, with units units_act, in region r].',
        category='User Input',
    ),
    'prc_aoff': SetDef(
        name='prc_aoff (r,p,y1,y2)',
        base_name='prc_aoff',
        aliases=(),
        indexes=('r', 'p', 'y1', 'y2'),
        description='Set of quadruples {r,p,y1,y2} such that process p cannot operate (activity is zero) between the years y1 and y2 in region r; note that y1 may be \'BOH\' for first year of first period and y2 may be \'EOH\' for last year of last period.',
        category='User Input',
    ),
    'prc_capunt': SetDef(
        name='prc_capunt (r,p,cg,units_cap)',
        base_name='prc_capunt',
        aliases=(),
        indexes=('r', 'p', 'cg', 'units_cap'),
        description='Definition of capacity unit of process p [set of quadruples {r,p,cg,units_cap} such that process p uses commodity group cg and units units_cap to define its capacity in region r].',
        category='User Input',
    ),
    'prc_desc': SetDef(
        name='prc_desc (r,p)',
        base_name='prc_desc',
        aliases=(),
        indexes=('r', 'p'),
        description='Processes by region, only to facilitate different descriptions by region. The elements are pairs {r,p}, for which the process description is specified according to the GAMS syntax.',
        category='User Input',
    ),
    'prc_dscncap': SetDef(
        name='prc_dscncap (r,p)',
        base_name='prc_dscncap',
        aliases=(),
        indexes=('r', 'p'),
        description='Set of processes p to be modelled using the lumpy investment formulation in region r; Default: empty set. If p is not in this set, then any lumpy investment parameters provided for p are ignored.',
        category='User Input',
    ),
    'prc_foff': SetDef(
        name='prc_foff (r,p,c,s,y1,y2)',
        base_name='prc_foff',
        aliases=(),
        indexes=('r', 'p', 'c', 's', 'y1', 'y2'),
        description='Set of sextuples specifying that the flow of commodity c at process p and timeslice s is not available between the years y1 and y2 in region r; note that y1 may be \'BOH\' for first year of first period and y2 may be \'EOH\' for last year of last period.',
        category='User Input',
    ),
    'prc_grp': SetDef(
        name='prc_grp',
        base_name='prc_grp',
        aliases=(),
        indexes=(),
        description='List of process groups; internally established in MAPLIST.DEF as: CHP, DISTR, DMD, ELE, HPL, IRE, MISC, PRE, PRV, PRW, REF, RENEW, XTRACT, NST, STG, STK, STS. The user may augment this list with any additional groups desired. The following predefined groups affect the data processing carried out by the model generator, and should not be deleted by the user: CHP, DISTR, DMD, ELE, HPL, IRE, PRE, PRV, PRW, REF, NST, STG, STK and STS.',
        category='Internal',
    ),
    'prc_map': SetDef(
        name='prc_map (r,prc_grp,p)',
        base_name='prc_map',
        aliases=(),
        indexes=('r', 'prc_grp', 'p'),
        description='Grouping of processes into process groups (prc_grp) [set of triplets {r,prc_grp,p} such that process p belongs to group prc_grp in region r]. Note: used strictly for reporting purposes.',
        category='User Input',
    ),
    'prc_noff': SetDef(
        name='prc_noff (r,p,y1,y2)',
        base_name='prc_noff',
        aliases=(),
        indexes=('r', 'p', 'y1', 'y2'),
        description='Set of quadruples {r,p,y1,y2} such that new capacity of process p cannot be installed between the years y1 and y2 in region r; note that y1 may be \'BOH\' for first year of first period and y2 may be \'EOH\' for last year of last period.',
        category='User Input',
    ),
    'prc_nstts': SetDef(
        name='prc_nstts (r,p,s)',
        base_name='prc_nstts',
        aliases=(),
        indexes=('r', 'p', 's'),
        description='Set of triplets {r,p,s} such that process p is a night storage device with charging timeslices s in region r; note that for night storage devices the commodity entering and the commodity leaving the storage may be different, as defined via the set top.',
        category='User Input',
    ),
    'prc_pkaf': SetDef(
        name='prc_pkaf (all_r,p)',
        base_name='prc_pkaf',
        aliases=(),
        indexes=('all_r', 'p'),
        description='Set of pairs {all_r,p} such that the availability factor (ncap_af) is to be used as value for the fraction of capacity of process p that can contribute to the peaking constraints (ncap_pkcnt), in region r.',
        category='User Input',
    ),
    'prc_pkno': SetDef(
        name='prc_pkno (all_r,p)',
        base_name='prc_pkno',
        aliases=(),
        indexes=('all_r', 'p'),
        description='Set of pairs {all_r,p}such that process p cannot be used in the peaking constraints in region r.',
        category='User Input',
    ),
    'prc_rcap': SetDef(
        name='prc_rcap (r,p)',
        base_name='prc_rcap',
        aliases=(),
        indexes=('r', 'p'),
        description='Set of pairs {r,p}such that early retirements are activated for process p in region r.',
        category='User Input',
    ),
    'prc_ts': SetDef(
        name='prc_ts (all_r,p,s)',
        base_name='prc_ts',
        aliases=('prc_ts2',),
        indexes=('all_r', 'p', 's'),
        description='Set of triplets {all_r,p,s} such that process p can operate at timeslice s in region r; Default: all timeslices on the timeslice level specified by prc_tsl.',
        category='User Input',
    ),
    'prc_tsl': SetDef(
        name='prc_tsl (r,p,tslvl)',
        base_name='prc_tsl',
        aliases=(),
        indexes=('r', 'p', 'tslvl'),
        description='Set of triplets {r,p,tslvl} such that process p can operate at timeslice level tslvl in region r; Default: \'ANNUAL\' timeslice level.',
        category='User Input',
    ),
    'prc_vint': SetDef(
        name='prc_vint (r,p)',
        base_name='prc_vint',
        aliases=(),
        indexes=('r', 'p'),
        description='Set of processes p that are vintaged technologies in region r, i.e. technical characteristics are tied to when the capacity was installed, not the current period; Default: process is not vintaged; note that vintaging increases the model size.',
        category='User Input',
    ),
    'r': SetDef(
        name='r (all_reg)',
        base_name='r',
        aliases=('reg',),
        indexes=('all_reg',),
        description='Set of internal regions; Subset of all_r.',
        category='User Input',
    ),
    's': SetDef(
        name='s',
        base_name='s',
        aliases=('all_ts', 'ts', 's2', 'sl'),
        indexes=(),
        description='Set of all timeslices (define the sub-annual divisions of a period). Timeslices effectively defined for specific processes and technologies are subsets of this set.',
        category='User Input',
    ),
    'side': SetDef(
        name='side',
        base_name='side',
        aliases=(),
        indexes=(),
        description='Index of constraint sides; internally fixed to the elements \'LHS\', \'RHS\'',
        category='Internal',
    ),
    't': SetDef(
        name='t (year)',
        base_name='t',
        aliases=('milestonyr', 'tt'),
        indexes=('year',),
        description='Set of representative years (middle years) for the model periods within the modelling horizon.',
        category='User Input',
    ),
    'teg': SetDef(
        name='teg (p)',
        base_name='teg',
        aliases=(),
        indexes=('p',),
        description='Set of technologies selected for endogenous technology learning; Subset of set p; if p not in teg, then any ETL investment parameters provided are ignored.',
        category='User Input',
    ),
    'top': SetDef(
        name='top (r,p,c,io)',
        base_name='top',
        aliases=(),
        indexes=('r', 'p', 'c', 'io'),
        description='RES topology definition indicating that commodity c enters (io=’IN’) or leaves (io=\'OUT\') the process p [set of quadruples {r,p,c,io} such that process p has a flow of commodity c with orientation io in region r].',
        category='User Input',
    ),
    'top_ire': SetDef(
        name='top_ire (all_reg,com, all_r,c,p)',
        base_name='top_ire',
        aliases=(),
        indexes=('all_reg', 'com', 'all_r', 'c', 'p'),
        description='RES topology definition for trade between regions [Set of quintuples indicating that commodity com from region all_reg is traded (exported) via exchange process p (where it is imported) into region all_r as commodity c]; note: the name of the traded commodity may be different in the two regions. By using all_reg=all_r, one can also define bi-directional processes within a region, e.g. for modeling transmission lines.',
        category='User Input',
    ),
    'ts_group': SetDef(
        name='ts_group (all_r,tslvl,s)',
        base_name='ts_group',
        aliases=(),
        indexes=('all_r', 'tslvl', 's'),
        description='Set of triplets {all_r,tslvl,s} such that timeslice s belongs to the timeslice level tslvl in region r; needed for the definition of the timeslice tree; only default is that the \'ANNUAL\' timeslice belongs to the \'ANNUAL\' timeslice level.',
        category='User Input',
    ),
    'ts_map': SetDef(
        name='ts_map (all_r,s,ts)',
        base_name='ts_map',
        aliases=(),
        indexes=('all_r', 's', 'ts'),
        description='Set of triplets {all_r,s,ts} such that s is an intermediate node s of the timeslice tree (neither \'ANNUAL\' nor the lowest level), and ts is a node directly under s in region r; the set is further extended by allowing ts = s (see figure 1).',
        category='User Input',
    ),
    'ts_off': SetDef(
        name='ts_off (r,ts,y1,y2)',
        base_name='ts_off',
        aliases=(),
        indexes=('r', 'ts', 'y1', 'y2'),
        description='Set of quadruples {r,ts,y1,y2} such that the timeslice branch consisting of the timeslice ts and all the timeslices below it will not be taken into account in the model between the years y1 and y2 in region r; note that y1 may be \'BOH\' for first year of first period and y2 may be \'EOH\' for last year of last period. The timeslice ts specified in ts_off must be directly below ANNUAL in the timeslice tree specified (usually at the SEASON level).',
        category='User Input',
    ),
    'tslvl': SetDef(
        name='tslvl',
        base_name='tslvl',
        aliases=(),
        indexes=(),
        description='Index of timeslice levels; internally fixed to the elements \'ANNUAL\', \'SEASON\', \'WEEKLY\', \'DAYNITE\'.',
        category='Internal',
    ),
    'u': SetDef(
        name='u',
        base_name='u',
        aliases=(),
        indexes=(),
        description='List of all units; maintained in the file UNITS.DEF.',
        category='User Input',
    ),
    'uc_attr': SetDef(
        name='uc_attr (r,uc_n,side, uc_grptype, uc_name)',
        base_name='uc_attr',
        aliases=(),
        indexes=('r', 'uc_n', 'side', 'uc_grptype', 'uc_name'),
        description='Set of quintuples such that the UC modifier specified by the uc_name (e.g., cost, conversion factor, etc.) will be applied to the coefficient for the variable identified by uc_grptype in the user constraint uc_n, for the side side (\'LHS\' or \'RHS\') in region r; if uc_name=\'GROWTH\' the user constraint represents a growth constraint.',
        category='User Input',
    ),
    'uc_cost': SetDef(
        name='uc_cost',
        base_name='uc_cost',
        aliases=(),
        indexes=(),
        description='Internally fixed list of cost types that can be used as modifier attributes in user constraints: COST, DELIV, TAX, SUB',
        category='Internal',
    ),
    'uc_dyndir': SetDef(
        name='uc_dyndir (r,uc_n,side)',
        base_name='uc_dyndir',
        aliases=(),
        indexes=('r', 'uc_n', 'side'),
        description='If side = \'RHS\', indicator for growth constraints to be generated between the periods t–1 and t; if side = \'LHS\', the set is ignored.',
        category='User Input',
    ),
    'uc_gmap_c': SetDef(
        name='uc_gmap_c (r,uc_n,uc_grptype,c)',
        base_name='uc_gmap_c',
        aliases=(),
        indexes=('r', 'uc_n', 'uc_grptype', 'c'),
        description='Indicator that a commodity variable (VAR_COMCON or VAR_COMPRD) for commodity (c) in a region (r) appears in a user constraint (uc_n).',
        category='User Input',
    ),
    'uc_gmap_p': SetDef(
        name='uc_gmap_p (r,uc_n,uc_grptype,p)',
        base_name='uc_gmap_p',
        aliases=(),
        indexes=('r', 'uc_n', 'uc_grptype', 'p'),
        description='Indicator that a variable (VAR_ACT, VAR_NCAP or VAR_CAP) associated with a process (p) in a region (r) appears in a user constraint (uc_n).',
        category='User Input',
    ),
    'uc_gmap_u': SetDef(
        name='uc_gmap_u (r,uc_n,ucn)',
        base_name='uc_gmap_u',
        aliases=(),
        indexes=('r', 'uc_n', 'ucn'),
        description='Indicator that a variable (VAR_UCRT) associated with a user constraint (ucn) in a region (r) appears in another user constraint (uc_n).',
        category='User Input',
    ),
    'uc_grptype': SetDef(
        name='uc_grptype',
        base_name='uc_grptype',
        aliases=(),
        indexes=(),
        description='Index of internally fixed key types of variables: ACT, FLO, IRE, CAP, NCAP, COMPRD, COMNET, COMCON, UCN These are used in association with the user constraints.',
        category='Internal',
    ),
    'uc_map_flo': SetDef(
        name='uc_map_flo (uc_n,r,p,c)',
        base_name='uc_map_flo',
        aliases=(),
        indexes=('uc_n', 'r', 'p', 'c'),
        description='Indicator that the flow variable (VAR_FLO) for region r, process p and commodity c is involved in user constraint uc_n.',
        category='User Input',
    ),
    'uc_map_ire': SetDef(
        name='uc_map_ire (uc_n,r,p,c)',
        base_name='uc_map_ire',
        aliases=(),
        indexes=('uc_n', 'r', 'p', 'c'),
        description='Indicator that an import/export (according to top_ire) trade variable (VAR_IRE) for region r, process p, and commodity c is involved in a user constraint (uc_n).',
        category='User Input',
    ),
    'uc_n': SetDef(
        name='uc_n',
        base_name='uc_n',
        aliases=('ucn',),
        indexes=(),
        description='List of user specified unique indicators of the user constraints.',
        category='User Input',
    ),
    'uc_name': SetDef(
        name='uc_name',
        base_name='uc_name',
        aliases=(),
        indexes=(),
        description='List of internally fixed indicators for attributes able to be referenced as coefficients in user constraints (e.g. the flow variable may be multiplied by the attribute FLO_COST in a user constraint if desired): COST, DELIV, TAX, SUB, EFF, NET, BUILDUP, CAPACT, CAPFLO, GROWTH, NEWFLO, ONLINE, PERIOD, PERDISC, INVCOST, INVTAX, INVSUB, CUMSUM, SYNC, YES See Section 6.4.6 for more detailed information.',
        category='Internal',
    ),
    'uc_r_each': SetDef(
        name='uc_r_each (all_r,uc_n)',
        base_name='uc_r_each',
        aliases=(),
        indexes=('all_r', 'uc_n'),
        description='Set of pairs {all_r,uc_n} such that the user constraint uc_n is to be generated for each specified region all_r.',
        category='User Input',
    ),
    'uc_r_sum': SetDef(
        name='uc_r_sum (all_r,uc_n)',
        base_name='uc_r_sum',
        aliases=(),
        indexes=('all_r', 'uc_n'),
        description='Set of pairs {all_r,uc_n} indicating that the user constraint uc_n is summing over all specified regions all_r (that is these constraints do not have a region index). Note that depending on the specified regions in uc_r_sum, the summation may be done only over a subset of all model regions. For example if the model contains the regions FRA, GER, ESP and one wants to create a user constraint called GHG summing over the regions FRA and GER but not ESP, the set uc_r_sum contains has the two entries {\'FRA\', \'GHG\'} and {\'GER\', \'GHG\'}.',
        category='User Input',
    ),
    'uc_t_each': SetDef(
        name='uc_t_each (r,uc_n,t)',
        base_name='uc_t_each',
        aliases=(),
        indexes=('r', 'uc_n', 't'),
        description='Indicator that the user constraint uc_n is to be generated for each specified period t.',
        category='User Input',
    ),
    'uc_t_succ': SetDef(
        name='uc_t_succ (r,uc_n,t)',
        base_name='uc_t_succ',
        aliases=(),
        indexes=('r', 'uc_n', 't'),
        description='Indicator that the user constraint uc_n is to be generated between the two successive periods t and t+1.',
        category='User Input',
    ),
    'uc_t_sum': SetDef(
        name='uc_t_sum (r,uc_n,t)',
        base_name='uc_t_sum',
        aliases=(),
        indexes=('r', 'uc_n', 't'),
        description='Indicator that the user constraint uc_n is to be generated summing over the periods t.',
        category='User Input',
    ),
    'uc_ts_each': SetDef(
        name='uc_ts_each (r,uc_n,s)',
        base_name='uc_ts_each',
        aliases=(),
        indexes=('r', 'uc_n', 's'),
        description='Indicator that the user constraint uc_n will be generated for each specified timeslice s.',
        category='User Input',
    ),
    'uc_ts_sum': SetDef(
        name='uc_ts_sum (r,uc_n,s)',
        base_name='uc_ts_sum',
        aliases=(),
        indexes=('r', 'uc_n', 's'),
        description='Indicator that the user constraint uc_n is to be generated summing over the specified timeslice s.',
        category='User Input',
    ),
    'uc_tsl': SetDef(
        name='uc_tsl (r,uc_n,side,tslvl)',
        base_name='uc_tsl',
        aliases=(),
        indexes=('r', 'uc_n', 'side', 'tslvl'),
        description='Indicator of the target timeslice level tslvl of a timeslice-dynamic (or pseudo-dynamic) user constraint uc_n.',
        category='User Input',
    ),
    'unit': SetDef(
        name='unit',
        base_name='unit',
        aliases=(),
        indexes=(),
        description='List of capacity blocks that can be added in lumpy investment option; default elements 0–100; the element \'0\' describes the case when no capacity is added.',
        category='Internal',
    ),
    'v': SetDef(
        name='v',
        base_name='v',
        aliases=('modlyear',),
        indexes=(),
        description='Union of the sets pastyear and t corresponding to all the years (periods) of a model run (thus actually an internal set).',
        category='Internal',
    ),
    'ww': SetDef(
        name='ww',
        base_name='ww',
        aliases=('allsow', 'w'),
        indexes=(),
        description='States of the world that can be used; default elements 1–64; under user control by the dollar control parameter $SET MAXSOW <n> in the <case>.RUN file',
        category='User Input',
    ),
    'year': SetDef(
        name='year',
        base_name='year',
        aliases=('allyear', 'll'),
        indexes=(),
        description='Years that can be used in the model; default range 1850-2200; under user control by the dollar control parameters $SET BOTIME <y> and $SET EOTIME <y> in the <case>.RUN file.',
        category='User Input',
    ),
    'afs': SetDef(
        name='afs (r,t,p,s,bd)',
        base_name='afs',
        aliases=(),
        indexes=('r', 't', 'p', 's', 'bd'),
        description='Indicator that the internal parameter COEF_AF, which is used as coefficient of the capacity (new investment variable VAR_NCAP plus past investments NCAP_PASTI) in the capacity utilization constraint EQ(l)_CAPACT, exists.',
        category='Internal',
    ),
    'bohyear': SetDef(
        name='bohyear (*)',
        base_name='bohyear',
        aliases=(),
        indexes=('*',),
        description='Set allyear plus element \'BOH\' (Beginning Of Horizon).',
        category='Internal',
    ),
    'dm_year': SetDef(
        name='dm_year (year)',
        base_name='dm_year',
        aliases=(),
        indexes=('year',),
        description='Union of sets datayear and modlyear',
        category='Internal',
    ),
    'eachyear': SetDef(
        name='eachyear (year)',
        base_name='eachyear',
        aliases=(),
        indexes=('year',),
        description='Set of all years between scalars MINYR (first year needed for cost calculation in objective function) and MIYR_VL + DUR_MAX (estimation of last year possible cost terms may occur).',
        category='Internal',
    ),
    'eohyear': SetDef(
        name='eohyear (*)',
        base_name='eohyear',
        aliases=(),
        indexes=('*',),
        description='Set allyear plus element \'EOH\' (Ending OF Horizon)',
        category='Internal',
    ),
    'eohyears': SetDef(
        name='eohyears (year)',
        base_name='eohyears',
        aliases=(),
        indexes=('year',),
        description='Set of all years between scalars MINYR (first year needed for cost calculation in objective function) and MIYR_VL (last year of model horizon).',
        category='Internal',
    ),
    'finest': SetDef(
        name='finest (r,s)',
        base_name='finest',
        aliases=(),
        indexes=('r', 's'),
        description='Set of finest timeslices s used in region r.',
        category='Internal',
    ),
    'fs_emis': SetDef(
        name='fs_emis (r,p,cg,c,com)',
        base_name='fs_emis',
        aliases=(),
        indexes=('r', 'p', 'cg', 'c', 'com'),
        description='Indicator that the flow variable (VAR_FLO) associated with emission com can be replaced by the flow variable of c multiplied by the emission factor FLO_SUM, which is used in the transformation equation (EQ_PTRANS) between the commodity group cg and the commodity com; used in the reduction algorithm (see Part III).',
        category='Internal',
    ),
    'g_rcur': SetDef(
        name='g_rcur (r,cur)',
        base_name='g_rcur',
        aliases=(),
        indexes=('r', 'cur'),
        description='Indicator of main currency cur by region r. For regions having several discounted currencies, the one having highest present value factors is selected; used for undiscounting the solution marginals.',
        category='Internal',
    ),
    'invspred': SetDef(
        name='invspred (year,jot,k,y)',
        base_name='invspred',
        aliases=(),
        indexes=('year', 'jot', 'k', 'y'),
        description='Set of investment years y and commissioning years k belonging to the investment spread starting with year and having jot number of steps (used for investment and fixed cost accounting).',
        category='Internal',
    ),
    'invstep': SetDef(
        name='invstep (year,jot,y,jot)',
        base_name='invstep',
        aliases=(),
        indexes=('year', 'jot', 'y', 'jot'),
        description='Set of investment years y belonging to the investment spread starting with year and having jot number of steps (used for investment and fixed cost accounting).',
        category='Internal',
    ),
    'miyr_1': SetDef(
        name='miyr_1 (t)',
        base_name='miyr_1',
        aliases=(),
        indexes=('t',),
        description='First milestonyr.',
        category='Internal',
    ),
    'no_act': SetDef(
        name='no_act (r,p)',
        base_name='no_act',
        aliases=(),
        indexes=('r', 'p'),
        description='List of processes p in region r not requiring the activity variable; used in reduction algorithm',
        category='Internal',
    ),
    'no_cap': SetDef(
        name='no_cap (r,p)',
        base_name='no_cap',
        aliases=(),
        indexes=('r', 'p'),
        description='List of processes p in region r not having any capacity related input parameters; used in reduction algorithm.',
        category='Internal',
    ),
    'no_rvp': SetDef(
        name='no_rvp (r,v,p)',
        base_name='no_rvp',
        aliases=(),
        indexes=('r', 'v', 'p'),
        description='New investment in process p in region r is not possible in period v and previously installed capacity does not exist anymore.',
        category='Internal',
    ),
    'obj_1a': SetDef(
        name='obj_1a (r,v,p)',
        base_name='obj_1a',
        aliases=(),
        indexes=('r', 'v', 'p'),
        description='Investment case small investment (NCAP_ILED/D(v) <= G_ILEDNO) and no repetition of investment (NCAP_TLIFE + NCAP_ILED >= D(v)) for process p in region r and vintage period v.',
        category='Internal',
    ),
    'obj_1b': SetDef(
        name='obj_1b (r,v,p)',
        base_name='obj_1b',
        aliases=(),
        indexes=('r', 'v', 'p'),
        description='Investment case small investment (NCAP_ILED/D(v) <= G_ILEDNO) and repetition of investment (NCAP_TLIFE + NCAP_ILED < D(v)) for process p in region r and vintage period v.',
        category='Internal',
    ),
    'obj_2a': SetDef(
        name='obj_2a (r,v,p)',
        base_name='obj_2a',
        aliases=(),
        indexes=('r', 'v', 'p'),
        description='Investment case large investment (NCAP_ILED/D(v) > G_ILEDNO) and no repetition of investment (NCAP_TLIFE + NCAP_ILED >= D(v)) for process p in region r and vintage period v.',
        category='Internal',
    ),
    'obj_2b': SetDef(
        name='obj_2b (r,v,p)',
        base_name='obj_2b',
        aliases=(),
        indexes=('r', 'v', 'p'),
        description='Investment case large investment (NCAP_ILED/D(v) > G_ILEDNO) and repetition of investment (NCAP_TLIFE + NCAP_ILED < D(v)) for process p in region r and vintage period v.',
        category='Internal',
    ),
    'obj_idc': SetDef(
        name='obj_idc (r,v,p,life,k,age)',
        base_name='obj_idc',
        aliases=(),
        indexes=('r', 'v', 'p', 'life', 'k', 'age'),
        description='Summation control for calculating the interest during constriction (IDC) for investment Cases 2.a and 2.b.',
        category='Internal',
    ),
    'obj_sumii': SetDef(
        name='obj_sumii (r,v,p,life,y,jot)',
        base_name='obj_sumii',
        aliases=(),
        indexes=('r', 'v', 'p', 'life', 'y', 'jot'),
        description='Summation control for investment and capacity related taxes and subsidies of the in the annual objective function, with lifetime life, spread starting in commissioning year y, having jot number of steps in the spread, and vintage period v.',
        category='Internal',
    ),
    'obj_sumiii': SetDef(
        name='obj_sumiii (r,v,p,ll,k,y)',
        base_name='obj_sumiii',
        aliases=(),
        indexes=('r', 'v', 'p', 'll', 'k', 'y'),
        description='Summation control for decommissioning costs with for the running year index y of annual objective function, vintage period v, startup-year ll, and commissioning year k (e.g. for spreading decommissioning costs over decommissioning time).',
        category='Internal',
    ),
    'obj_sumiv': SetDef(
        name='obj_sumiv (r,v,p,life,y,jot)',
        base_name='obj_sumiv',
        aliases=(),
        indexes=('r', 'v', 'p', 'life', 'y', 'jot'),
        description='Summation control for fixed costs in the annual objective function with lifetime life, spread starting in commissioning year y, having jot number of steps in the spread, and vintage period v.',
        category='Internal',
    ),
    'obj_sumivs': SetDef(
        name='obj_sumivs (r,v,p,k,y)',
        base_name='obj_sumivs',
        aliases=(),
        indexes=('r', 'v', 'p', 'k', 'y'),
        description='Summation control for decommissioning surveillance costs with running year index y of annual objective function, vintage period v and commissioning year k.',
        category='Internal',
    ),
    'obj_sums': SetDef(
        name='obj_sums (r,v,p)',
        base_name='obj_sums',
        aliases=(),
        indexes=('r', 'v', 'p'),
        description='Indicator that process p in region r with vintage period v has a salvage value for investments with a (technical) lifetime that extends past the model horizon.',
        category='Internal',
    ),
    'obj_sums3': SetDef(
        name='obj_sums3 (r,v,p)',
        base_name='obj_sums3',
        aliases=(),
        indexes=('r', 'v', 'p'),
        description='Indicator that process p in region r with vintage period v has a salvage value associated with the decommissioning or surveillance costs.',
        category='Internal',
    ),
    'obj_sumsi': SetDef(
        name='obj_sumsi (r,v,p,k)',
        base_name='obj_sumsi',
        aliases=(),
        indexes=('r', 'v', 'p', 'k'),
        description='Indicator that for commissioning years k process p in region r with vintage period v has a salvage value due to investment, decommissioning or surveillance costs arising from the technical lifetime extending past the model horizon.',
        category='Internal',
    ),
    'periodyr': SetDef(
        name='periodyr (v,y)',
        base_name='periodyr',
        aliases=(),
        indexes=('v', 'y'),
        description='Mapping of individual years y to the modlyear (milestonyr or pastyear; v) period they belong to; if v is a pastyear, only the pastyear itself belongs to the period; for the last period of the model horizon also the years until the very end of the model accounting horizon (MIYR_VL + DUR_MAX) are elements of periodyr.',
        category='Internal',
    ),
    'prc_act': SetDef(
        name='prc_act (r,p)',
        base_name='prc_act',
        aliases=(),
        indexes=('r', 'p'),
        description='Indicator that a process p in region r needs an activity variable (used in reduction algorithm).',
        category='Internal',
    ),
    'prc_cap': SetDef(
        name='prc_cap (r,p)',
        base_name='prc_cap',
        aliases=(),
        indexes=('r', 'p'),
        description='Indicator that a process p in region r needs a capacity variable (used in reduction algorithm).',
        category='Internal',
    ),
    'prc_spg': SetDef(
        name='prc_spg (r,p,cg)',
        base_name='prc_spg',
        aliases=(),
        indexes=('r', 'p', 'cg'),
        description='Shadow primary group (SPG) of a process p; all commodities on the opposite process side of the primary commodity group (PCG) which have the same commodity type as the PCG, usually internally determined (though it may be specified by the user under special circumstances (e.g., when not all the commodities on the opposite side of the process, which should be in the SPG, are of the same commodity type com_type). If no commodity of the same type is found: if PCG is of type \'DEM\' and process is a material processing process (PRV or PRW), then the SPG contains all material commodities on the SPG side; otherwise the SPG is selected as the first type among the commodity types on the SPG side, in the flowing order: When PCG type is DEM: (NRG, MAT, ENV) When PCG type is NRG: (MAT, DEM, ENV) When PCG type is MAT: (NRG, DEM, ENV) When PCG type is ENV: (NRG, MAT, DEM)',
        category='Internal',
    ),
    'prc_stgips': SetDef(
        name='prc_stgips (r,p,c)',
        base_name='prc_stgips',
        aliases=(),
        indexes=('r', 'p', 'c'),
        description='Set of triplets {r,p,c} such that process p is an inter-period storage for the commodity c in region r; the commodity c enters and/or leaves the storage according to the set top; the storage can only operate at the ANNUAL level.',
        category='Internal',
    ),
    'prc_stgtss': SetDef(
        name='prc_stgtss (r,p,c)',
        base_name='prc_stgtss',
        aliases=(),
        indexes=('r', 'p', 'c'),
        description='Set of triplets {r,p,c} such that process p is a storage process between timeslices (e.g., seasonal hydro reservoir, day/night pumped storage) for commodity c in region r; commodity c enters and/or leaves the storage according to set top; the storage operates at the timeslice level prc_tsl.',
        category='Internal',
    ),
    'rc': SetDef(
        name='rc (r,c)',
        base_name='rc',
        aliases=(),
        indexes=('r', 'c'),
        description='List of all commodities c found in region r.',
        category='Internal',
    ),
    'rc_agp': SetDef(
        name='rc_agp (r,c,lim)',
        base_name='rc_agp',
        aliases=(),
        indexes=('r', 'c', 'lim'),
        description='Indicator of which commodities c are aggregated into other commodities by aggregation type lim.',
        category='Internal',
    ),
    'rc_cumcom': SetDef(
        name='rc_cumcom (r,com_var,y1,y2,c)',
        base_name='rc_cumcom',
        aliases=(),
        indexes=('r', 'com_var', 'y1', 'y2', 'c'),
        description='Indicator of a cumulative constraint of type com_var defined for commodity c between years y1 and y2',
        category='Internal',
    ),
    'rcj': SetDef(
        name='rcj (r,c,j,bd)',
        base_name='rcj',
        aliases=(),
        indexes=('r', 'c', 'j', 'bd'),
        description='Steps j used in direction bd for the elastic demand formulation of commodity c.',
        category='Internal',
    ),
    'rcs_combal': SetDef(
        name='rcs_combal (r,t,c,s,bd)',
        base_name='rcs_combal',
        aliases=(),
        indexes=('r', 't', 'c', 's', 'bd'),
        description='Indicator of which timeslices (s) associate with commodity c in region r for time period t the commodity balance equation (EQ(l)_COMBAL) is to be generated, with a constraint type corresponding to bd.',
        category='Internal',
    ),
    'rcs_comprd': SetDef(
        name='rcs_comprd (r,t,c,s,bd)',
        base_name='rcs_comprd',
        aliases=(),
        indexes=('r', 't', 'c', 's', 'bd'),
        description='Indicator of which timeslices (s) associate with commodity c in region r for time period t the commodity production equation (EQ(l)_COMBAL) is to be generated, with a constraint type according to bd, when a corresponding rhs_comprd indicator exists.',
        category='Internal',
    ),
    'rcs_comts': SetDef(
        name='rcs_comts (r,c,s)',
        base_name='rcs_comts',
        aliases=(),
        indexes=('r', 'c', 's'),
        description='All timeslices s being at or above timeslice level (com_tsl) of commodity c in region r.',
        category='Internal',
    ),
    'rdcur': SetDef(
        name='rdcur (r,cur)',
        base_name='rdcur',
        aliases=(),
        indexes=('r', 'cur'),
        description='List of currencies cur that are discounted (G_DRATE provided) in each region r.',
        category='Internal',
    ),
    'rhs_combal': SetDef(
        name='rhs_combal (r,t,c,s)',
        base_name='rhs_combal',
        aliases=(),
        indexes=('r', 't', 'c', 's'),
        description='Indicator that the commodity net variable (VAR_COMNET) is required in commodity balance (EQE_COMBAL), owing to bounds/costs imposed on the net amount.',
        category='Internal',
    ),
    'rhs_comprd': SetDef(
        name='rhs_comprd (r,t,c,s)',
        base_name='rhs_comprd',
        aliases=(),
        indexes=('r', 't', 'c', 's'),
        description='Indicator that the commodity production variable (VAR_COMPRD) is required in commodity balance (EQE_COMPRD), owing to a limit/costs imposed on the production.',
        category='Internal',
    ),
    'rp': SetDef(
        name='rp (r,p)',
        base_name='rp',
        aliases=(),
        indexes=('r', 'p'),
        description='List of processes (p) in each region (r).',
        category='Internal',
    ),
    'rp_aire': SetDef(
        name='rp_aire (r,p,ie)',
        base_name='rp_aire',
        aliases=(),
        indexes=('r', 'p', 'ie'),
        description='List of exchange processes (p) in each region (r) with indicators (ie) corresponding to the activity being defined by imports/exports or both.',
        category='Internal',
    ),
    'rp_flo': SetDef(
        name='rp_flo (r,p)',
        base_name='rp_flo',
        aliases=(),
        indexes=('r', 'p'),
        description='List of all processes in region (r), except inter-regional exchange processes (ire).',
        category='Internal',
    ),
    'rp_inout': SetDef(
        name='rp_inout (r,p,io)',
        base_name='rp_inout',
        aliases=(),
        indexes=('r', 'p', 'io'),
        description='Indicator as to whether a process (p) in a region (r) is input or output (io = \'IN\'/\'OUT\') normalized with respect to its activity.',
        category='Internal',
    ),
    'rp_ire': SetDef(
        name='rp_ire (all_r,p)',
        base_name='rp_ire',
        aliases=(),
        indexes=('all_r', 'p'),
        description='List of inter-regional exchange processes (p) found in each region (all_r).',
        category='Internal',
    ),
    'rp_pg': SetDef(
        name='rp_pg (r,p,cg)',
        base_name='rp_pg',
        aliases=(),
        indexes=('r', 'p', 'cg'),
        description='The primary commodity group (cg) of each process (p) in a region (r).',
        category='Internal',
    ),
    'rp_pgtype': SetDef(
        name='rp_pgtype (r,p,com_type)',
        base_name='rp_pgtype',
        aliases=(),
        indexes=('r', 'p', 'com_type'),
        description='The commodity type (com_type) of primary commodity group of a process (p) in a region (r).',
        category='Internal',
    ),
    'rp_sgs': SetDef(
        name='rp_sgs (r,p)',
        base_name='rp_sgs',
        aliases=(),
        indexes=('r', 'p'),
        description='List of those standard processes (p) in each region (r), which have been defined to have a night storage (NST) capability.',
        category='Internal',
    ),
    'rp_std': SetDef(
        name='rp_std (r,p)',
        base_name='rp_std',
        aliases=(),
        indexes=('r', 'p'),
        description='List of standard processes (p) in each region (r).',
        category='Internal',
    ),
    'rp_stg': SetDef(
        name='rp_stg (r,p)',
        base_name='rp_stg',
        aliases=(),
        indexes=('r', 'p'),
        description='List of storage processes (p) in each region (r).',
        category='Internal',
    ),
    'rp_sts': SetDef(
        name='rp_sts (r,p)',
        base_name='rp_sts',
        aliases=(),
        indexes=('r', 'p'),
        description='List of generalized timeslice storage processes (p) in each region (r).',
        category='Internal',
    ),
    'rp_upl': SetDef(
        name='rp_upl (r,p,lim)',
        base_name='rp_upl',
        aliases=(),
        indexes=('r', 'p', 'lim'),
        description='List of those processes (p) in each region (r) that have dispatching attributes ACT_MINLD/ACT_UPS defined, with qualifier lim.',
        category='Internal',
    ),
    'rp_ups': SetDef(
        name='rp_ups (r,p,tslvl,lim)',
        base_name='rp_ups',
        aliases=(),
        indexes=('r', 'p', 'tslvl', 'lim'),
        description='Timeslices (s) of a process (p) in a region (r) during which start-ups are permitted (used for processes in the set rp_upl(r,p,\'FX\'))',
        category='Internal',
    ),
    'rpc': SetDef(
        name='rpc (r,p,c)',
        base_name='rpc',
        aliases=(),
        indexes=('r', 'p', 'c'),
        description='List of commodities (c) associated with a process p in region r (by top or top_ire).',
        category='Internal',
    ),
    'rpc_act': SetDef(
        name='rpc_act (r,p,c)',
        base_name='rpc_act',
        aliases=(),
        indexes=('r', 'p', 'c'),
        description='Indicator that the primary commodity group of a process (p), except exchange processes (see rpc_aire) consists of only one commodity (c), enabling the corresponding flow variable to be replaced by the activity variable (used in reduction algorithm).',
        category='Internal',
    ),
    'rpc_aire': SetDef(
        name='rpc_aire (r,p,c)',
        base_name='rpc_aire',
        aliases=(),
        indexes=('r', 'p', 'c'),
        description='Indicator that the primary commodity group of an exchange process (p) consists of only one commodity (c), enabling the corresponding flow variable to be replaced by the activity variable (used in reduction algorithm).',
        category='Internal',
    ),
    'rpc_capflo': SetDef(
        name='rpc_capflo (r,v,p,c)',
        base_name='rpc_capflo',
        aliases=(),
        indexes=('r', 'v', 'p', 'c'),
        description='Indicator that a commodity flow c in region r is associated with the capacity of a process (p, due to NCAP_ICOM, NCAP_OCOM, or NCAP_COM being provided).',
        category='Internal',
    ),
    'rpc_cumflo': SetDef(
        name='rpc_cumflo (r,p,c,y1,y2)',
        base_name='rpc_cumflo',
        aliases=(),
        indexes=('r', 'p', 'c', 'y1', 'y2'),
        description='Indicator of a cumulative constraint defined for commodity flow c of process p between years y1 and y2',
        category='Internal',
    ),
    'rpc_noflo': SetDef(
        name='rpc_noflo (r,p,c)',
        base_name='rpc_noflo',
        aliases=(),
        indexes=('r', 'p', 'c'),
        description='A subset of rpc_capflo indicating those processes (p) in a region (r) where a commodity (c) is only consumed or produced through capacity based flows, and thus has no flow variable for the commodity.',
        category='Internal',
    ),
    'rpc_emis': SetDef(
        name='rpc_emis (r,p,cg)',
        base_name='rpc_emis',
        aliases=(),
        indexes=('r', 'p', 'cg'),
        description='Indicator that the flow variable of an emission commodity (cg) associated with process (p) in a region (r) can be replaced by the fuel flow causing the emission multiplied by the emission factor (used in reduction algorithm).',
        category='Internal',
    ),
    'rpc_eqire': SetDef(
        name='rpc_eqire (r,p,c)',
        base_name='rpc_eqire',
        aliases=(),
        indexes=('r', 'p', 'c'),
        description='Indicator of the commodities (c) associated with inter-regional exchange processes (p) in region (r) for which an inter-region exchange equation (EQ_IRE) is to be generated; the set does not contain the marketplace region (rpc_market).',
        category='Internal',
    ),
    'rpcc_ffunc': SetDef(
        name='rpcc_ffunc (r,p,c)',
        base_name='rpcc_ffunc',
        aliases=(),
        indexes=('r', 'p', 'c'),
        description='Flow variable of a commodity (c) associated with a process (p) that can be replaced by another flow variable of the process, due to a direct FLO_FUNC or FLO_SUM relationship.',
        category='Internal',
    ),
    'rpc_ire': SetDef(
        name='rpc_ire (all_r,p,c,ie)',
        base_name='rpc_ire',
        aliases=(),
        indexes=('all_r', 'p', 'c', 'ie'),
        description='Commodities (c) imported or exported (ie=\'IMP\'/\'EXP\') via process p in a region (all_r).',
        category='Internal',
    ),
    'rpc_market': SetDef(
        name='rpc_market (all_r,p,c,ie)',
        base_name='rpc_market',
        aliases=(),
        indexes=('all_r', 'p', 'c', 'ie'),
        description='List of market regions (subset of all_r) that trade a commodity (c) through a process (p) either by only multidirectional export links (ie=\'EXP\') or by both import and export links (ie=\'IMP\'). The market structure is user-defined through the set top_ire.',
        category='Internal',
    ),
    'rpc_pg': SetDef(
        name='rpc_pg (r,p,cg,c)',
        base_name='rpc_pg',
        aliases=(),
        indexes=('r', 'p', 'cg', 'c'),
        description='Mapping of the commodities (c) in a region (r) that belong to the primary commodity group (cg) associated with process p.',
        category='Internal',
    ),
    'rpc_spg': SetDef(
        name='rpc_spg (r,p,c)',
        base_name='rpc_spg',
        aliases=(),
        indexes=('r', 'p', 'c'),
        description='The list of commodities (c) in a region (r) belonging to the shadow primary group of process (p).',
        category='Internal',
    ),
    'rpc_stg': SetDef(
        name='rpc_stg (r,p,c)',
        base_name='rpc_stg',
        aliases=(),
        indexes=('r', 'p', 'c'),
        description='List of stored (charged/discharged) commodities (c) of storage processes (p) in region (r).',
        category='Internal',
    ),
    'rpc_stgn': SetDef(
        name='rpc_stgn (r,p,c,io)',
        base_name='rpc_stgn',
        aliases=(),
        indexes=('r', 'p', 'c', 'io'),
        description='List of those stored (charged/discharged) commodities (c) of storage processes (p) in region (r), which are connected to the commodity balance on one side (io) only.',
        category='Internal',
    ),
    'rpcg_ptran': SetDef(
        name='rpcg_ptran (r,p,c1,c2,cg1,cg2)',
        base_name='rpcg_ptran',
        aliases=(),
        indexes=('r', 'p', 'c1', 'c2', 'cg1', 'cg2'),
        description='Indicator of the transformation equations (EQ_PTRANS) that can be eliminated by the reduction algorithm.',
        category='Internal',
    ),
    'rpcs_var': SetDef(
        name='rpcs_var (r,p,c,s)',
        base_name='rpcs_var',
        aliases=(),
        indexes=('r', 'p', 'c', 's'),
        description='The list of valid timeslices for the flow variable (VAR_FLO) of commodity c associated with process p in region r; flow variables of commodities which are part of the primary commodity group have the timeslice resolution of the process (prc_tsl), while all other flow variables are created according to the rps_s1 timeslices.',
        category='Internal',
    ),
    'rps_prcts': SetDef(
        name='rps_prcts (r,p,s)',
        base_name='rps_prcts',
        aliases=(),
        indexes=('r', 'p', 's'),
        description='All (permitted) timeslices (s) at or above the process (p) timeslice level (prc_tsl) in a region (r).',
        category='Internal',
    ),
    'rps_s1': SetDef(
        name='rps_s1 (r,p,s)',
        base_name='rps_s1',
        aliases=(),
        indexes=('r', 'p', 's'),
        description='All (permitted) timeslices (s) belonging to the finest timeslice level of the process (p, prc_tsl) and the commodity timeslice level (com_tsl) of the shadow primary commodity group.',
        category='Internal',
    ),
    'rps_s2': SetDef(
        name='rps_s2 (r,p,s)',
        base_name='rps_s2',
        aliases=(),
        indexes=('r', 'p', 's'),
        description='For an ANNUAL level NST process, contains all permitted timeslices (s) at the level above the finest commodity timeslice levels (com_tsl) of the shadow primary group (spg). For all other processes, rps_s2 = rps_s1.',
        category='Internal',
    ),
    'rps_stg': SetDef(
        name='rps_stg (r,p,s)',
        base_name='rps_stg',
        aliases=(),
        indexes=('r', 'p', 's'),
        description='Process level timeslices (s) of timeslice storage process (p) in a region (r).',
        category='Internal',
    ),
    'rreg': SetDef(
        name='rreg (all_reg,all_r)',
        base_name='rreg',
        aliases=(),
        indexes=('all_reg', 'all_r'),
        description='Indicator that trade exists from region all_reg to region all_r.',
        category='Internal',
    ),
    'rs_below': SetDef(
        name='rs_below (all_r,ts,s)',
        base_name='rs_below',
        aliases=(),
        indexes=('all_r', 'ts', 's'),
        description='All timeslices (s) strictly below the higher timeslice (ts) in the timeslice tree.',
        category='Internal',
    ),
    'rs_below1': SetDef(
        name='rs_below1 (all_r,ts,s)',
        base_name='rs_below1',
        aliases=(),
        indexes=('all_r', 'ts', 's'),
        description='All timeslices (s) immediately (one level) below the higher timeslice (ts) in the timeslice tree.',
        category='Internal',
    ),
    'rs_tree': SetDef(
        name='rs_tree (all_r,ts,s)',
        base_name='rs_tree',
        aliases=(),
        indexes=('all_r', 'ts', 's'),
        description='For a timeslice (ts) all timeslices (s) that are on the same paths within the timeslice tree, e.g. if ts=SP_WD in Fig. 6, valid timeslices s are: ANNUAL, SP, SP_WD, SP_WD_D, SP_WD_N',
        category='Internal',
    ),
    'rtc_cumnet': SetDef(
        name='rtc_cumnet (r,t,c)',
        base_name='rtc_cumnet',
        aliases=(),
        indexes=('r', 't', 'c'),
        description='Indicator that the commodity net variable (VAR_COMNET) for commodity c in region r for period t has a cumulative bound applied.',
        category='Internal',
    ),
    'rtc_cumprd': SetDef(
        name='rtc_cumprd (r,t,c)',
        base_name='rtc_cumprd',
        aliases=(),
        indexes=('r', 't', 'c'),
        description='Indicator that the commodity production variable (VAR_COMPRD) for commodity c in region r for period t has a cumulative bound applied.',
        category='Internal',
    ),
    'rtcs_sing': SetDef(
        name='rtcs_sing (r,t,c,s,io)',
        base_name='rtcs_sing',
        aliases=(),
        indexes=('r', 't', 'c', 's', 'io'),
        description='Indicator that a commodity c is not available in a specific period t and timeslice s, since the all the processes producing (io=\'OUT\') or consuming it (io=\'IN\') are turned-off. In the case of io=\'OUT\', the commodity is not available, meaning that processes having only this commodity as input cannot operate. Similar reasoning applies to the case io=\'IN\'.',
        category='Internal',
    ),
    'rtcs_varc': SetDef(
        name='rtcs_varc (r,t,c,s)',
        base_name='rtcs_varc',
        aliases=(),
        indexes=('r', 't', 'c', 's'),
        description='For commodity (c) in region (r) indicator for the timeslices (s) and the periods (t) the commodity is available.',
        category='Internal',
    ),
    'rtp': SetDef(
        name='rtp = rvp (r,v,p)',
        base_name='rtp',
        aliases=(),
        indexes=(),
        description='Indication of the periods and pastyears for which process (p) in region (r) is available; all other RTP_* control sets are based on this set.',
        category='Internal',
    ),
    'rtp_cptyr': SetDef(
        name='rtp_cptyr (r,v,t,p)',
        base_name='rtp_cptyr',
        aliases=(),
        indexes=('r', 'v', 't', 'p'),
        description='For each vintage period (v) an indication of the periods (t) for which newly installed capacity of process (p) in a region (r) is available, taking into account construction lead-time (NCAP_ILED) and technical lifetime (NCAP_TLIFE).',
        category='Internal',
    ),
    'rtp_off': SetDef(
        name='rtp_off (r,t,p)',
        base_name='rtp_off',
        aliases=(),
        indexes=('r', 't', 'p'),
        description='Indication of the periods (t) in which no new investment is permitted for a process (p) in a region (r).',
        category='Internal',
    ),
    'rtp_vara': SetDef(
        name='rtp_vara (r,t,p)',
        base_name='rtp_vara',
        aliases=(),
        indexes=('r', 't', 'p'),
        description='Indication of the periods (t) for which a process (p) in a region (r) is available.',
        category='Internal',
    ),
    'rtp_varp': SetDef(
        name='rtp_varp (r,t,p)',
        base_name='rtp_varp',
        aliases=(),
        indexes=('r', 't', 'p'),
        description='Indicator that the capacity variable (VAR_CAP) will be generated for process (p) in a region (r) in period (t).',
        category='Internal',
    ),
    'rtp_vintyr': SetDef(
        name='rtp_vintyr (r,v,t,p)',
        base_name='rtp_vintyr',
        aliases=(),
        indexes=('r', 'v', 't', 'p'),
        description='An indication of for which periods (t) a process (p) in a region (r) is available since it was first installed (v); for vintaged processes (prc_vint) identical to rtp_cptyr, for non-vintaged processes the v index in the rtp_cptyr entries is ignored by setting it to t (v = t).',
        category='Internal',
    ),
    'rtpc': SetDef(
        name='rtpc (r,t,p,c)',
        base_name='rtpc',
        aliases=(),
        indexes=('r', 't', 'p', 'c'),
        description='For a process (p) in a region (r) the combination of the periods it is available (rtp) and commodities associated with it (rpc).',
        category='Internal',
    ),
    'rtps_off': SetDef(
        name='rtps_off (r,t,p,s)',
        base_name='rtps_off',
        aliases=(),
        indexes=('r', 't', 'p', 's'),
        description='An indication for process (p) of the timeslices (s) for which the process is turned-off (used in reduction algorithm).',
        category='Internal',
    ),
    'rtpcs_varf': SetDef(
        name='rtpcs_varf (r,t,p,c,s)',
        base_name='rtpcs_varf',
        aliases=(),
        indexes=('r', 't', 'p', 'c', 's'),
        description='The list of valid timeslices (s) and periods (t) for the flow variable (VAR_FLO) of process (p) and commodity (c); taking into account the availability of the activity, capacity and flow (rtp_vara, rpcs_var and prc_foff). The timeslice level of a flow variable equals the process timeslice level (prc_tsl) when the flow is part of the primary commodity group of the process. Otherwise the timeslice level of a flow variable is set to the finest level of the commodities in the shadow group (SPG) or the process level, whichever is finer.',
        category='Internal',
    ),
}
